steps:
  - name: 'gcr.io/cloud-builders/gcloud'
  args: [
      - 'compute'
      - 'instances'
      - 'create'
      - 'gcptest-vm1'          
      - '--zone=us-west1-b'         
      - '--machine-type=n1-standard-2'  
      - '--image-family=windows-2019'   
      - '--image-project=windows-cloud' 
      - '--boot-disk-size=50GB'         
      - '--boot-disk-type=pd-standard'  
      - '--metadata', 'windows-startup-script-ps1=net user admin-user admin123 /add; net localgroup administrators admin-user /add'
  ]

serviceAccount: '928001221137@cloudbuild.gserviceaccount.com'
logsBucket: 'gs://exercise_test_bucket-1'
timeout: '1000s'

substitutions:
  _INSTANCE_NAME: 'gcptest-vm1'

