steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Create Compute Engine Instance'
    args:
      - 'compute'
      - 'instances'
      - 'create'
      - 'gcp-test-vm1'
      - '--zone=us-west1-c'
      - '--machine-type=n1-standard-2'
      - '--image-family=windows-2019'
      - '--image-project=windows-cloud'
      - '--boot-disk-size=50GB'
      - '--boot-disk-type=pd-standard'
      - '--metadata=windows-startup-script-ps1=Add-LocalUser -Name "admin-user" -Password (ConvertTo-SecureString "Admin123!" -AsPlainText -Force); Add-LocalGroupMember -Group "Administrators" -Member "admin-user"'
      - '--tags=http-server,https-server'

serviceAccount: '928001221137-compute@developer.gserviceaccount.com'
logsBucket: 'gs://exercise_test_bucket-1'
timeout: '1000s'

substitutions:
  _INSTANCE_NAME: 'gcp-test-vm1'
